name = "multiport-support"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "multiport-support-db"
database_id = "acf778af-1099-4c37-bc77-ae05c49f3708"
